"""Add transaction_id to Payment model

Revision ID: 0baef06afee7
Revises: 1581f8832b5c
Create Date: 2024-07-24 13:29:57.871688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '0baef06afee7'
down_revision: Union[str, None] = '1581f8832b5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('transaction_id', sa.String(), nullable=True))

    op.execute("""
            UPDATE payments
            SET transaction_id = 'dd7d51ef-980d-4e21-9531-c09f8e331302'
            WHERE id = 1
        """)

    op.alter_column('payments', 'transaction_id', existing_type=sa.String(), nullable=False)
    op.create_index(op.f('ix_payments_transaction_id'), 'payments', ['transaction_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_transaction_id'), table_name='payments')
    op.drop_column('payments', 'transaction_id')
    # ### end Alembic commands ###
